export const WEDDING_DATA = {
  groom: "Dr. Shini",
  groomParents: "G.D/o Lt. Mrs Suman & Lt Mr. Narendranath Choubey(Paternal)\nLt. Mrs. Kanti Devi & Lt Mr. Santosh K Chaturvedi(Maternal)",
  bride: "Dr. Piyush",
  brideParents: "S/o Dr. Usha & Dr. Dinesh Sharma",
  introMessage: "Mr. Anurag Choubey(H/o Lt. Mrs. Anju) invite you to\nthe Wedding ceremony of their beloved daughter",
  withText: "With",
  togetherText: "Together with our families & friends",
  requestText: "REQUEST THE HONOUR OF YOUR PRESENCE",
  datesSummary: "01 – 04 DECEMBER 2026 • NARNAUL & ORCHHA",
  weddingDateFormatted: "3rd - 4th DECEMBER 2026",
  weddingDayOfWeek: "THURSDAY,FRIDAY",
  weddingTimeFormatted: "AT 5:00 PM",
  targetTimestamp: new Date("2026-12-03T17:00:00+05:30").getTime(),
  venueName: "Raj Vilas Palace",
  venueAddress: "Orchha, Madhya Pradesh",
  googleMapsUrl: "https://maps.app.goo.gl/SjAinaMEUt6Tcjgt7?g_st=ic",
  travelInfo: {
    airport: "Gwalior Airport (GWL)",
    railwayStation: "Orchha Railway Station",
  },
  venues: [
    {
      id: "destination",
      step: 1,
      badge: "Destination Wedding Venue",
      phaseTitle: "Royal Destination Celebrations",
      name: "Raj Vilas Palace",
      subtitle: "Heritage Palace & Resort",
      address: "Raj Vilas Palace, Orchha, Madhya Pradesh",
      dates: "3rd, 4th & 5th December 2026",
      keyHighlights: "Mehendi · Royal Sangeet · Haldi · Wedding Ceremony · Vidai",
      departureNote: "All destination wedding festivities, banquet dinner & royal stay",
      airport: "Gwalior Airport (GWL)",
      railwayStation: "Orchha Railway Station",
      googleMapsEmbed: "https://maps.google.com/maps?q=Raj+Vilas+Orchha+Madhya+Pradesh&t=m&z=14&output=embed",
      googleMapsUrl: "https://maps.app.goo.gl/SjAinaMEUt6Tcjgt7?g_st=ic",
    },
  ],
  welcomeMessage:
    "“With hearts full of joy,\nwe warmly invite you to celebrate the wedding of our beloved daughter.\n\nYour presence and blessings will make this joyous occasion truly special.”",
  whatsappNumber: "+91 8108306532",
  whatsappRawNumber: "918108306532",
  events: [
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Krishav Lawn, Raj Vilas Palace, Orchha (MP)",
      date: "Thursday, 03 December 2026",
      time: "12:30 PM",
      title: "Mehendi Ceremony",
      desc: "An auspicious afternoon adorned with intricate henna designs, vibrant folk music, and joyous celebration.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Arnav Hall, Raj Vilas Palace, Orchha (MP)",
      date: "Thursday, 03 December 2026",
      time: "7:00 PM",
      title: "Sangeet Ceremony",
      desc: "A magical royal evening of dance performances, musical revelry, and grand celebration with family and friends.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Utsav Courtyard, Raj Vilas Palace, Orchha (MP)",
      date: "Friday, 04 December 2026",
      time: "11:00 AM",
      title: "Haldi Ceremony",
      desc: "A blissful celebration with sacred turmeric paste, floral blessings, music, and joyful laughter.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Chatarbhuj Lawn, Raj Vilas Palace, Orchha (MP)",
      date: "Friday, 04 December 2026",
      time: "5:30 PM onwards",
      title: "Wedding Ceremony",
      desc: "The sacred Varmala, auspicious Vedic Pheras, and eternal vows followed by royal banquet dinner.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Raj Vilas Palace, Orchha (MP)",
      date: "Saturday, 05 December 2026",
      time: "9:00 AM",
      title: "Vidai Ceremony",
      desc: "Heartfelt blessings and affectionate farewell as the newlyweds begin their lifelong journey of love and togetherness.",
    },
  ],
};

export const SCRATCH_PALETTE = {
  gradStart: "#fde2e8",
  gradMid: "#c97a8c",
  gradEnd: "#4a1525",
  speckLightRgb: "253, 226, 232",
  speckMidRgb: "201, 122, 140",
  speckDarkRgb: "74, 21, 37",
  sparkleRgb: "255, 240, 245",
  revealBg: "#ffffff",
  heartBorder: "#8b233a",
  titleColor: "#8b233a",
  dateColor: "#2b141b",
  dayColor: "#8b233a",
  timeColor: "#45202a",
};
