export const WEDDING_DATA = {
  groom: "Dr. Shini",
  groomParents: "G.D/o Lt. Mrs Suman & Lt Mr. Narendranath Choubey(Paternal)\nLt. Mrs. Kanti Devi & Lt Mr. Santosh K Chaturvedi(Maternal)",
  bride: "Dr. Piyush",
  brideParents: "S/o Dr. Usha & Dr. Dinesh Sharma",
  introMessage: "Mr. Anurag Choubey(H/o Lt. Mrs. Anju) invite you to\nthe Wedding ceremony of their beloved daughter",
  withText: "With",
  togetherText: "Together with our families & friends",
  requestText: "REQUEST THE HONOUR OF YOUR PRESENCE",
  datesSummary: "01 – 04 DECEMBER 2026 • NARNAUL & ORCHHA",
  weddingDateFormatted: "3rd - 4th DECEMBER 2026",
  weddingDayOfWeek: "THURSDAY,FRIDAY",
  weddingTimeFormatted: "AT 5:00 PM",
  targetTimestamp: new Date("2026-12-01T17:00:00+05:30").getTime(),
  venueName: "Raj Vilas Palace",
  venueAddress: "Orchha, Madhya Pradesh",
  googleMapsUrl: "https://maps.app.goo.gl/SjAinaMEUt6Tcjgt7?g_st=ic",
  venues: [
    {
      id: "barat",
      step: 1,
      badge: "Location 1 · Baraat Starting Point",
      phaseTitle: "Baraat & Home Ceremonies",
      name: "Pooja Hospital",
      subtitle: "At our residence",
      address: "Pooja Hospital, Narnaul, Haryana",
      dates: "1st – 2nd December 2026",
      keyHighlights: "Lagan Ceremony · Nikashi & Dinner · Baraat Departure at 11:00 PM",
      departureNote: "Baraat will depart on 2nd Dec at 11:00 PM by Bus from Narnaul to Orchha, MP",
      googleMapsEmbed: "https://maps.google.com/maps?q=Pooja+Hospital+Narnaul+Haryana&t=m&z=15&output=embed",
      googleMapsUrl: "https://maps.google.com/?q=Pooja+Hospital+Narnaul+Haryana",
    },
    {
      id: "destination",
      step: 2,
      badge: "Location 2 · Destination Wedding",
      phaseTitle: "Royal Destination Celebrations",
      name: "Raj Vilas Palace",
      subtitle: "Heritage Palace & Resort",
      address: "Raj Vilas Palace, Orchha, Madhya Pradesh",
      dates: "3rd, 4th & 5th December 2026",
      keyHighlights: "Mehendi · Royal Sangeet · Haldi · Wedding Ceremony · Vidai",
      departureNote: "All destination wedding festivities, banquet dinner & royal stay",
      googleMapsEmbed: "https://maps.google.com/maps?q=Raj+Vilas+Orchha+Madhya+Pradesh&t=m&z=14&output=embed",
      googleMapsUrl: "https://maps.app.goo.gl/SjAinaMEUt6Tcjgt7?g_st=ic",
    },
  ],
  welcomeMessage:
    "“With hearts full of joy,\nwe warmly invite you to celebrate the wedding of our beloved son.\n\nYour presence and blessings will make this joyous occasion truly special.”",
  whatsappNumber: "+91 82969 52770",
  whatsappRawNumber: "918296952770",
  events: [
    {
      step: 1,
      phase: "Home Ceremonies",
      locationTag: "Narnaul",
      venueName: "At our residence, Pooja Hospital, Narnaul",
      date: "Tuesday, 01 December 2026",
      time: "5:00 PM",
      dinnerTime: "7:00 PM",
      title: "Lagan Ceremony",
      desc: "Auspicious commencement of wedding celebrations with sacred lagan rituals, followed by celebratory dinner at 7:00 PM.",
    },
    {
      step: 1,
      phase: "Home Ceremonies",
      locationTag: "Narnaul",
      venueName: "Pooja Hospital, Narnaul",
      date: "Wednesday, 02 December 2026",
      time: "7:00 PM",
      dinnerTime: "8:00 PM",
      title: "Nikashi Ceremony",
      desc: "Traditional Nikashi ceremony and pre-departure blessings, followed by festive dinner at 8:00 PM.",
    },
    {
      step: 1,
      phase: "Baraat Journey",
      locationTag: "Journey to Orchha",
      venueName: "Departure by Bus from Pooja Hospital, Narnaul",
      date: "Wednesday, 02 December 2026",
      time: "11:00 PM",
      title: "Baraat Departure",
      desc: "The royal Baraat will embark at 11:00 PM by Bus from Narnaul, traveling overnight to Raj Vilas Palace, Orchha (MP).",
      isJourney: true,
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Raj Vilas Palace, Orchha (MP)",
      date: "Thursday, 03 December 2026",
      time: "12:30 PM",
      title: "Mehendi Ceremony",
      desc: "An auspicious afternoon adorned with intricate henna designs, vibrant folk music, and joyous celebration.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Raj Vilas Palace, Orchha (MP)",
      date: "Thursday, 03 December 2026",
      time: "7:00 PM",
      title: "Sangeet Ceremony",
      desc: "A magical royal evening of dance performances, musical revelry, and grand celebration with family and friends.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Raj Vilas Palace, Orchha (MP)",
      date: "Friday, 04 December 2026",
      time: "11:00 AM",
      title: "Haldi Ceremony",
      desc: "A blissful celebration with sacred turmeric paste, floral blessings, music, and joyful laughter.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Raj Vilas Palace, Orchha (MP)",
      date: "Friday, 04 December 2026",
      time: "5:30 PM onwards",
      title: "Wedding Ceremony",
      desc: "The sacred Varmala, auspicious Vedic Pheras, and eternal vows followed by royal banquet dinner.",
    },
    {
      step: 2,
      phase: "Destination Wedding",
      locationTag: "Orchha, MP",
      venueName: "Raj Vilas Palace, Orchha (MP)",
      date: "Saturday, 05 December 2026",
      time: "9:00 AM",
      title: "Vidai Ceremony",
      desc: "Heartfelt blessings and affectionate farewell as the newlyweds begin their lifelong journey of love and togetherness.",
    },
  ],
};

export const SCRATCH_PALETTE = {
  gradStart: "#fde2e8",
  gradMid: "#c97a8c",
  gradEnd: "#4a1525",
  speckLightRgb: "253, 226, 232",
  speckMidRgb: "201, 122, 140",
  speckDarkRgb: "74, 21, 37",
  sparkleRgb: "255, 240, 245",
  revealBg: "#ffffff",
  heartBorder: "#8b233a",
  titleColor: "#8b233a",
  dateColor: "#2b141b",
  dayColor: "#8b233a",
  timeColor: "#45202a",
};
